### ISSUE TITLE
Suggest to loosen the dependency on uvicorn

### ISSUE THREAD

**Issue by Agnes-U** [antonio-pedro99/fastapi_notes#3]
Dear developers, 

Your project fastapi_notes requires "uvicorn==0.13.4" in its dependency. After analyzing the source code, we found that the following versions of uvicorn can also be suitable without affecting your project, i.e., uvicorn 0.13.0, 0.13.1, 0.13.2, 0.13.3. Therefore, we suggest to loosen the dependency on uvicorn from "uvicorn==0.13.4" to "uvicorn>=0.13.0,<=0.13.4" to avoid any possible conflict for importing more packages or for downstream projects that may use ddos_script. 

May I pull a request to further loosen the dependency on uvicorn?

By the way, could you please tell us whether such dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

<br />

----

Details: 

Your project (commit id: 7a9608b8261f673fbd091fb8c1f4f90bf380d102) directly uses 1 APIs from package uvicorn.

```
uvicorn.main.run
```

Beginning fromwhich, 37 functions are then indirectly called, including 19 uvicorn's internal APIs and 18 outsider APIs as follows:
```
[/antonio-pedro99/fastapi_notes]
+--uvicorn.main.run
|      +--uvicorn.config.Config.__init__
|      |      +--uvicorn.config.Config.configure_logging
|      |      |      +--logging.config.dictConfig
|      |      |      +--json.load
|      |      |      +--logging.config.fileConfig
|      |      |      +--yaml.safe_load
|      |      +--os.getcwd
|      |      +--dotenv.load_dotenv
|      |      +--os.environ.get
|      +--uvicorn.server.Server.__init__
|      |      +--uvicorn.server.ServerState.__init__
|      +--sys.exit
|      +--uvicorn.config.Config.bind_socket
|      |      +--socket.socket
|      |      +--sys.exit
|      |      +--click.style
|      +--uvicorn.supervisors.watchgodreload.WatchGodReload.__init__
|      |      +--uvicorn.supervisors.basereload.BaseReload.__init__
|      |      |      +--threading.Event
|      |      |      +--os.getpid
|      |      +--pathlib.Path
|      |      +--uvicorn.supervisors.watchgodreload.CustomWatcher.__init__
|      |      |      +--re.compile
|      |      |      +--watchgod.DefaultWatcher.__init__
|      +--uvicorn.supervisors.basereload.BaseReload.run
|      |      +--uvicorn.supervisors.basereload.BaseReload.startup
|      |      |      +--click.style
|      |      |      +--signal.signal
|      |      |      +--uvicorn.subprocess.get_subprocess
|      |      |      |      +--sys.stdin.fileno
|      |      +--uvicorn.supervisors.basereload.BaseReload.should_restart
|      |      +--uvicorn.supervisors.basereload.BaseReload.restart
|      |      |      +--uvicorn.subprocess.get_subprocess
|      |      +--uvicorn.supervisors.basereload.BaseReload.shutdown
|      |      |      +--click.style
|      +--uvicorn.supervisors.multiprocess.Multiprocess.__init__
|      |      +--threading.Event
|      |      +--os.getpid
|      +--uvicorn.supervisors.multiprocess.Multiprocess.run
|      |      +--uvicorn.supervisors.multiprocess.Multiprocess.startup
|      |      |      +--click.style
|      |      |      +--signal.signal
|      |      |      +--uvicorn.subprocess.get_subprocess
|      |      +--uvicorn.supervisors.multiprocess.Multiprocess.shutdown
|      |      |      +--click.style
|      +--uvicorn.server.Server.run
|      |      +--asyncio.get_event_loop
```

Since all these functions have not been changed between any version for package "uvicorn" from [0.13.0, 0.13.1, 0.13.2, 0.13.3] and 0.13.4. Therefore, we believe it is safe to loosen the corresponding dependency.

**Comment by antonio-pedro99** [comment]
Hey @Agnes-U 
Thanks for raising this issue. 
Any contribution is welcome, please feel free to open a pull request with further changes.
I would appreciate if you mention this issue on your PR so that it gets closed as soon as the PR gets closed too.

**Comment by Agnes-U** [comment]
Thank you for your reply! I found that this modification has been merged before, [here](https://github.com/antonio-pedro99/fastapi_notes/commit/9c20a34b99695522db3af98f6657ff407999ef64), thanks~
